### ISSUE TITLE
Create University Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#1]
Create a page for creating a university. Given that it does not require navigation and should block other actions, a dialog window would probably be apt.

## Tasks
- [x] Create UI
- [x] Bind to the ViewModel
- [x] Add form validation
- [x] Hook up to the database for persistence.
