### ISSUE TITLE
Microsoft Store App Deployment

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#14]
After seeing the results of #11, while it is possible to distribute the app manually, it would be cleaner to use the Microsoft Store directly instead.

## Tasks
- [x] Make a Microsoft Store developer account
- [x] Publish the app to the Microsoft Store
  - [x] Make the app private for only myself and my father

**Comment by kazeraniman** [comment]
Theoretically it has been released on the Microsoft Store (according to the dashboard) but I can't see it so this ticket will stay up until I can.

**Comment by kazeraniman** [comment]
I just added and removed emails repeatedly (with different capitalization), logged on and off of different Microsoft accounts while following the link or being on the link page and eventually I could see it.
