### ISSUE TITLE
Generic Message Dialog

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#18]
It's handy to have a generic message dialog box so that I can show information to the user. I would prefer to not use it for everything (for example, it would be annoying on all errors and successes) but it is a good thing to have at this point in the project so I can spam it where I need it and can improve the UX later as needed.

## Tasks
- [x] Dialog window that displays a message and buttons.
  - [x] Title
  - [x] Body
  - [ ] Primary button
  - [x] Optional secondary button
  - [x] Button themes
- [x] Service to launch the window from anywhere without having to use interactions (good for MVVM but bad for usability so I'll sidestep it here for now).
