### ISSUE TITLE
Database Service

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#2]
Set up a system to create the database, apply migrations, and then actually use the database for data storage and retrieval. This database service will potentially be injected for use with DI at a later point, but I may start off with a singleton or statics just to get the ball rolling faster. I would like to try out some DI libraries though.

As this is a simple app and multiple users and crazy requirements are not desired, I'll go with a sqlite database to allow for syncing via OneDrive for the simplicity that my father requested.

## Tasks
- [x] Set up libraries to handle the DB
- [x] System for storing and retrieving the location of the database for use
- [x] Method for creation of database
- [x] Method for migration of database
- [x] Basic attempts at data storage and retrieval to confirm functionality
