### ISSUE TITLE
Create Course Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#23]
Create a page for creating a course.

## Tasks
- [x] Create UI
- [x] Bind to the ViewModel
- [x] Add form validation
- [x] Hook up to the database for persistence.
