### ISSUE TITLE
Toast Messages

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#35]
In order to avoid being annoying, where I would normally use toast messages I'm currently doing nothing as the closes equivalent in the project at the moment is a dialog box and that would be very intrusive. I would like to create a toast message system (possibly using a flyout as a resource on the main window) that would allow for some generic messages to be displayed (e.g. object created, edited, or deleted).

## Tasks
- [x] Create a toast message system
- [x] Toast message on object creation
- [x] Toast message on object edit
- [x] Toast message on object deletion
