### ISSUE TITLE
Create Student Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#37]
Create a page for creating a student.

## Tasks
- [x] Create UI
- [x] Bind to the ViewModel
- [ ] Add form validation
- [x] Hook up to the database for persistence.
