### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#47]
There should be a place where settings can be modified. This will be even more important for items that can't be defaulted, like the name to use on a study plan for the export.

## Tasks
- [x] Create a settings page
- [x] Allow for the settings to be modified
- [x] Separate the button for the settings page from the other pages
