### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#5]
Create a form of navigation between the different main pages of the app. This just concerns itself with the sidebar and switching views; the actual pages come in different issues.

## Tasks
- [x] Create a side bar
- [x] Change the page based on the nav button clicked
- [x] Transition between the pages smoothly
- [x] Only show the main page when the app is loaded (e.g. database is connected)
