### ISSUE TITLE
Create Study Plan Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#50]
Create a page for creating a study plan.

## Tasks
- [x] Create UI
- [x] Bind to the ViewModel
- [x] Add form validation
- [x] Hook up to the database for persistence.
- [x] Only create the necessary parts
  - [x] Student
  - [x] Destination University
    - [x] Different from student's university
  - [x] Default Everything else
