### ISSUE TITLE
Edit Study Plan Page

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#51]
Create a page for creating a study plan. Study plans are more complicated than other models so the creation and editing windows are disjoint.

## Tasks
- [x] Display unchanging properties
  - [x] Student
  - [x] Destination University
- [x] Allow changing properties
  - [x] Status
  - [x] Academic term
  - [x] Seasonal term
  - [x] Year
  - [x] Due date
  - [x] Notes
  - [x] Home university courses
  - [x] Equivalent destination university courses
- [x] Show equivalencies between the courses
