### ISSUE TITLE
Export Study Plan

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#53]
The study plan should be exportable for use. There is a template so it needs to be filled according to that. Making the template from scratch in code is a pain so I'll try [MiniWord](https://github.com/mini-software/MiniWord) instead.

## Tasks
- [x] Create a template
  - [x] Ensure the template isn't committed in case it is proprietary
- [x] Fill out the template based on the current data
  - [ ] Sort the courses by equivalency
- [x] Save to the desired location
