### ISSUE TITLE
Resizable Windows

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#60]
My father's laptop has a smaller screen so the Windows buttons are off-screen by default which is annoying. Sizing should be adjusted to fix this.

## Tasks
- [ ] Shrink all windows in size.
- [ ] Make all windows resizable by the user.
- [ ] Ensure that scroll views are present to be able to see the content regardless.
