### ISSUE TITLE
Study Plan Export

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#61]
Similar to the Credit Transfer Memo, allow for the export of a study plan in the new template.

## Tasks
- [ ] Create a new template for the study plan form.
- [ ] Add in the required database fields to back the new, needed information.
- [ ] Add in the required form fields to back the new, needed information.
- [ ] Add in a button for the new export.
