### ISSUE TITLE
Update Credit Transfer Memo Template

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#62]
Some changes were requested to the Credit Transfer Memo export so the template should be adjusted to allow for that.

## Tasks
- [ ] Move the student ID to a new line.
- [ ] Insert the names of the host and destination university in the table headers.
- [ ] Change the date format to match the other form.
