### ISSUE TITLE
Study Plan Export Template Location

### ISSUE THREAD

**Issue by kazeraniman** [kazeraniman/CourseEquivalencyDesktop#63]
Currently the study plan templates are bundled with the app which makes it difficult for them to be modified by the end user as they have to go through the development and publishing process to make changes. Instead, the templates should be specified by the user so they can be easily adjusted (although that puts the burden of correctness on them).

## Tasks
- [ ] Add in settings for the location of the Credit Transfer Memo and Study Plan templates.
- [ ] Allow them to be changed on the settings page.
- [ ] Replace the use of the in-built templates with these.
